# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, image_paths):
        self.image_paths = image_paths
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 731, 511))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../data/draft/Screenshot 2024-06-12 163832.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 550, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 550, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 550, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(620, 550, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton_4.clicked.connect(self.show_next)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tool version 2"))
        self.pushButton.setText(_translate("MainWindow", "undo"))
        self.pushButton_2.setText(_translate("MainWindow", "straight"))
        self.pushButton_3.setText(_translate("MainWindow", "curved"))
        self.pushButton_4.setText(_translate("MainWindow", "next"))
        
    def show_next(self):
        try:
            self.label.setPixmap(QtGui.QPixmap(next(self.image_paths)))
        except:
            print("No more images to show")
            exit()
            
def get_all_image_paths(img_dir):
    import os
    image_names = os.listdir(img_dir)
    return iter([os.path.join(img_dir, image_name) for image_name in image_names])
        


if __name__ == "__main__":
    
    img_dir = '..\data\draft'
    image_paths = get_all_image_paths(img_dir)
    # for i in image_paths:
    #     print(i) 
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(image_paths=image_paths)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())